-- MySQL Script generated by MySQL Workbench
-- Tue Oct 14 12:21:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cadastro_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastro_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro_banco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cadastro_banco` ;

-- -----------------------------------------------------
-- Table `cadastro_banco`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro_banco`.`produtos` ;

CREATE TABLE IF NOT EXISTS `cadastro_banco`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(200) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidadeEstoque` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cadastro_banco`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro_banco`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `cadastro_banco`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `textFieldNome` VARCHAR(50) NOT NULL,
  `formattedTextFieldCPF` VARCHAR(14) NOT NULL,
  `grupoTipoUsuario` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `formattedTextFieldCPF` (`formattedTextFieldCPF` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
